# Generated by Django 5.1 on 2024-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_level', models.CharField(max_length=50)),
                ('available_equipment', models.TextField()),
                ('workout_time', models.IntegerField(help_text='Preferred workout duration in minutes')),
                ('goals', models.TextField(help_text="User's fitness goals")),
                ('generated_workout', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
